name: build

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: compile c and c++
        shell: cmd
        run: |
          echo #include "TinyHook.h" > test.cpp
          echo int main(){return 0;} >> test.cpp
          cl /nologo /W3 /EHsc test.cpp
          echo #include "TinyHook.h" > test.c
          echo int main(){return 0;} >> test.c
          cl /nologo /W3 test.c
          echo #define VMT_DXGI_HELPERS > test_features.cpp
          echo #define VMT_DX12_HELPERS >> test_features.cpp
          echo #include "TinyHook.h" >> test_features.cpp
          echo int main(){ return 0; } >> test_features.cpp
          cl /nologo /W3 /EHsc test_features.cpp
